apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: habast-top-tls
  namespace: myapp          
spec:
  secretName: habast-top-tls
  issuerRef:
    name: letsencrypt-staging   
    kind: ClusterIssuer
  commonName: habast.top
  dnsNames:
  - habast.top
  
