replicaCount: 2

image:
  repository: docker.io/kkattl/backend
  tag: latest                 
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  DB_ENDPOINT: postgres-postgresql.data.svc.cluster.local
  DATABASE: change
  USERNAME: change
  USERPASSWORD: change
  CACHE_ENDPOINT: redis-master.data.svc.cluster.local
  REDIS_HOST: redis-master.data.svc.cluster.local
  REDIS_PASS: ""

ingress:
  enabled: true
  host: habast.top
  path: /api              
  pathType: Prefix
  tls:
    enabled: true
    secretName: habast-top-tls
